export const ADD_TODO_STARTED = "ADD_TODO_STARTED"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE"

export const RETRIEVE_TODOS = "RETRIEVE_TODOS"
export const RETRIEVE_TODOS_SUCCESS = "RETRIEVE_TODOS_SUCCESS"
export const RETRIEVE_TODOS_FAILURE = "RETRIEVE_TODOS_FAILURE"

export const DELETE_TODO_STARTED = "DELETE_TODO_STARTED"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const TOGGLE_TODO_STARTED = "TOGGLE_TODO_STARTED"
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS"
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE"

export const SET_FILTER = "SET_FILTER"